Modify bootstrap workflow for dependency installation
Updated the GitHub Actions workflow to install dependencies and set up Traefik as a reverse proxy.

diff --git a/.github/workflows/bootstrap.yml b/.github/workflows/bootstrap.yml
--- a/.github/workflows/bootstrap.yml
+++ b/.github/workflows/bootstrap.yml
@@ -1,5 +1,5 @@
 #GitHub Action Deployment
-name: Server Bootstrap - Install Docker and Docker Compose
+name: Server Bootstrap - Install Dependencies
 
 on: workflow_dispatch
 
@@ -8,7 +8,7 @@ jobs:
     name: Build and deploy
     runs-on: ubuntu-latest
     steps:
-      - name: Execute remote SSH commands using key
+      - name: Install Docker and Docker Compose
         uses: appleboy/ssh-action@v1
         with:
           host: ${{ secrets.SERVER_HOST }}
@@ -41,4 +41,28 @@ jobs:
                 echo "Docker Compose: $COMPOSE_VERSION"
 
                 echo "Docker and Docker Compose installed successfully!"
-        
+
+      - name: Install and setup Traefik as reverse proxy
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+                # Update OS so Docker is accessible
+                sudo apt update && sudo apt upgrade -y
+                reboot
+
+                # Create external network for Traefik
+                docker network create traefik-net
+
+                 # Verify network installation for Traefik
+                echo "=== Checking network installation ==="
+                NETWORK=$(docker network ls | grep traefik-net)
+                if ! echo "$NETWORK" | grep -q "traefik-net"; then
+                echo "ERROR: Traefik network is not installed correctly."
+                exit 1
+                fi
+                echo "Traefik network: $NETWORK"
+
+                echo "Traefik network installed successfully!"
